version: 0.2

phases:
  install:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/jatkuvaprojektijpa-0.0.1-SNAPSHOT.jar
  discard-paths: yes
